# Generated by Django 6.0.2 on 2026-02-27 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=255, verbose_name='url-идентификатор')),
                ('description', models.TextField(blank=True, verbose_name='Описание категории')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Отображение')),
            ],
            options={
                'verbose_name': 'Категория услуг',
                'verbose_name_plural': 'Категории услуг',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('slug', models.SlugField(max_length=200, verbose_name='url-идентификатор')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.CharField(blank=True, max_length=100, verbose_name='Цена')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Отображение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='service.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['category', 'order', 'name'],
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
